### PR TITLE
feat: improve InfoPanel

### PR DESCRIPTION
**Pull request by wadjih-bencheikh18**
closes https://github.com/zakodium-oss/react-science/issues/710

### CODE REVIEW

**Review by lpatiny — APPROVED** [review]
I tried the branch and indeed the scroll bar is now at the correct place.

image

**Comment by stropitek** [comment]
@lpatiny is this ok? Seems not great that the panel does not reveal its content when opened, because it is not at the right scroll position.

https://github.com/zakodium-oss/react-science/assets/4118690/c4bad4e5-f06f-4d8e-9e55-fc5b729d29b9

**Comment by targos** [comment]
I think there should be I lay one sticky header and they should not accumulate

**Comment by lpatiny** [comment]
Indeed I didn't test with 2 sections and it is very confusing currently. I was not thinking that the title of the section were not scrolling but only that it does not scroll behind the search bar. On the other hand seeing in which section you are is an added value as well.

I agree with Michael that we should not accumulate the sticky header because it does not bring anything and it yields to the issue Daniel pointed out.

**Review by stropitek — APPROVED** [review]

**Pull request merged**
