### PR TITLE
feat: add more features to button component

### PR DESCRIPTION
**Pull request by hamed-musallam**

### CODE REVIEW

**Comment by targos** [comment]
Please remove the commits that are already on the main branch.

**Comment by targos** [comment]
Can you add examples in the `button.stories` to show the new API? Also, I'm not sure using white/black as the default color is good, because we don't see anything when the button is on a white background.

**Comment by targos** [comment]
can you please merge with the latest main branch (the folder with the components has been renamed)?

**Comment by hamed-musallam** [comment]
@targos 

i fixed the conflict, you can merge it if you want.

**Pull request closed without merging**
