### PR TITLE
feat: add select component

### PR DESCRIPTION
**Pull request by Xstoudi**
Work in progress, I still need to figure out why keyboard navigation is not working.

### CODE REVIEW

**Comment by stropitek** [comment]
Are you aware of https://github.com/zakodium-oss/react-science/issues/472?

**Comment by Xstoudi** [comment]
> Are you aware of #472?

Yes, I just forgot to ref the issue.

**Comment by Xstoudi** [comment]
Okay, keyboard navigation seems to be failing because `document.activeElement` stays the same even after changing focus.
[Select.tsx line 543](https://github.com/radix-ui/primitives/blob/eca6babd188df465f64f23f3584738b85dba610e/packages/react/select/src/Select.tsx#L543)

I'm not really sure what is causing this right now.

**Comment by targos** [comment]
Probably related to the shadow dom. We often have issues with libraries that don't work well in a shadow dom.

**Comment by Xstoudi** [comment]
I already had the problem with react libs to pinch/pan/zoom on elements. 

Radix seems to has some issues related to shadow dom:

https://github.com/radix-ui/primitives/issues/1980
https://github.com/radix-ui/primitives/issues/1772

**Comment by Xstoudi** [comment]
Deploy successfull, I think you can review. If we merge like this I'll open an issue.

**Comment by stropitek** [comment]
Behavior + API LGTM except for the issues you already mentioned.

Can you add an optional `style` prop (mainly to be flexible with the width of the select). I can merge after that.

I have a few comments on the visual look but will create separate issues for that.

**Comment by targos** [comment]
There are linter issues btw.

**Comment by Xstoudi** [comment]
I fixed linting errors and added the option to pass style props to the root element.

**Pull request merged**
