### PR TITLE
Reduce size of toolbar in the panels

### PR DESCRIPTION
**Pull request by wadjih-bencheikh18**
closes : https://github.com/zakodium-oss/react-science/issues/679

### CODE REVIEW

**Comment by stropitek** [comment]
I'm not in favour of this. The icons look blurry.

The icons are made to be displayed 16x16 and there is not much we can do about it because smaller versions of the icons do not exist.

@lpatiny

**Comment by targos** [comment]
16x16 seems to be a standard size for small icons, we should not try to make it smaller or people will have trouble to see them.

**Comment by wadjih-bencheikh18** [comment]
@targos Do I close this PR?

**Comment by targos** [comment]
I think so, yes

**Pull request closed without merging**
