### PR TITLE
Use stacked panel for measurement info panel

### PR DESCRIPTION
**Pull request by wadjih-bencheikh18**
Closes : https://github.com/zakodium-oss/react-science/issues/650
Closes : https://github.com/zakodium-oss/react-science/issues/651

### CODE REVIEW

**Comment by wadjih-bencheikh18** [comment]
I got insperation from weight and biases platform
image

**Comment by stropitek** [comment]
The new layout with grouped action in the table header is great 👍🏻 

I noticed that the issue with the direction of the animation is still there (so not a storybook issue afterall?). I'm creating another issue for that.

CleanShot 2024-02-12 at 11 38 44

In this PR, can you make this button a dropdown with the choices:
- View metadata - opens the measurements info panel (stacked). It should not have the confirm / close choices, only close. Choose an appropriate icon ("info" icon)
- Configure - opens the measurements configuration panel (stacked). Should also only have close choice, since editing the color of the spectrum has an immediate effect. Don't replace the measurement accordion panel yet, just add it as a stacked panel in the measurements.

**Comment by wadjih-bencheikh18** [comment]
> I noticed that the issue with the direction of the animation is still there (so not a storybook issue afterall?). I'm creating another issue for that.

Not the case for me, which navigator are you using?

**Comment by targos** [comment]
I can reproduce with Chrome and Firefox.

**Comment by wadjih-bencheikh18** [comment]
> In this PR, can you make this button a dropdown with the choices:

Implemented.

**Comment by stropitek** [comment]
Last thing: can the delete button remove selected instead of all.

Remove all should be select all then delete selected

**Comment by wadjih-bencheikh18** [comment]
> I found out that in local is diffrent then here.

Do you have any interpretation of that?
it works perfectly only in the developement version

**Comment by stropitek** [comment]
> Do you have any interpretation of that?
> it works perfectly only in the developement version

It's probably related to strict mode since it is enabled in the app and disabled in the storybook (and always disabled in prod).

So without strict mode it seems to not work.

Their documentation does not seem to be affected by that.
Maybe try to start see if you are able to have a working example based on their documentation. And then from that see how you need to change it to reproduce the bug.

**Comment by stropitek** [comment]
The most notable affect of using strict mode is to re-run effects in developments.

https://react.dev/reference/react/StrictMode

**Review by stropitek — APPROVED** [review]

**Pull request merged**
