### PR TITLE
Use blueprintjs HTMLTable

### LINKED ISSUE #583: Use blueprintjs HTMLTable component in the Table component
https://blueprintjs.com/docs/#core/components/html-table

Try to use the `HTMLTable` component to render the `Table` component and let's see if the look is improved.

Add controls to the story with the props provided by the `HTMLTable` component.

### PR DESCRIPTION
**Pull request by moonayyur**
closes #583

- Replace "Title" with "Header" to make the bordered property work in the `HTMLTable` header
- Add the color prop for `StyledTable`
- Remove `Controls` story (duplicate of `Control`)

### CODE REVIEW

**Comment by moonayyur** [comment]
@stropitek an error occurs when saving the file Table.tsx (since before blueprint integration):

> Error: invalid Table child
>     at splitChildren

It disappears after refreshing the page

**Comment by stropitek** [comment]
> @stropitek an error occurs when saving the file Table.tsx

@moonayyur what do you mean? Can you provide a link / screenshot / video to show it?

**Review by stropitek — COMMENTED** [review]
Is Table's `color` prop used anywhere? It does not seem very useful.

feat: use blueprint html table, adding bordered, compact, interactive and striped props

Breaking changes:
- Table's font size changed from 12px to 14px
- Table `border` prop renamed to `hasBorder`

@moonayyur are there any other breaking changes?

**Comment by moonayyur** [comment]
> @moonayyur what do you mean? Can you provide a link / screenshot / video to show it?

@stropitek 
image

**Comment by moonayyur** [comment]
> Is Table's color prop used anywhere? It does not seem very useful.

It is only use in `StyledTable` story, the text color doesn't change when modifying it using style due to the blueprint component

> @moonayyur are there any other breaking changes?

I think this one is important :
Replace "ValueRenderers.Title" with "ValueRenderers.Header" to make the bordered property work in the HTMLTable header

**Pull request merged**
