### PR TITLE
Use 14px as base font size

### PR DESCRIPTION
**Pull request by wadjih-bencheikh18**
closes : https://github.com/zakodium-oss/react-science/issues/607

### CODE REVIEW

**Comment by stropitek** [comment]
> The 2 parts highlighted in red were not there before and are added by this PR.

I am making this conclusion based on 
CleanShot 2024-02-12 at 14 13 31

**Comment by wadjih-bencheikh18** [comment]
> It seems like it changes what is displayed in the IR plot.

Yes, I have to fix the tests
Making the default font bigger change the display so the zoom result will change for sure.

**Comment by wadjih-bencheikh18** [comment]
Tests updated

**Comment by stropitek** [comment]
> Making the default font bigger change the display so the zoom result will change for sure.

Yes but a change it font shouldn't make the title of the plot appear / disappear
This hints to a potential bug in the implementation

I can merge since the title is now displayed as it should but maybe worth investigating

**Pull request merged**
