### PR TITLE
feat: make Table component compatible with styled components libraries

### PR DESCRIPTION
**Pull request by stropitek**

### CODE REVIEW

**Comment by stropitek** [comment]
It should be ok now.

**Comment by stropitek** [comment]
The specifics of what and how things should be displayed in the table remain to be discussed, but I think the PR can be merged as is and the rest can be improved later.

CleanShot 2024-12-11 at 10 59 38

**Comment by tpoisseau** [comment]
https://table-classname.react-science.pages.dev/stories/?path=%2Fstory%2Fcomponents-table--virtualized&args=bordered%3A%21true%3Bcompact%3A%21true%3Bstriped%3A%21true%3BstickyHeader%3A%21true

Looks good to me

**Comment by tpoisseau** [comment]
https://table-classname.react-science.pages.dev/stories/?path=%2Fstory%2Fcomponents-table--styled-table
Miss controls, I can't check with `striped`

**Review by tpoisseau — APPROVED** [review]
SGTM with story fixed

**Pull request merged**
