### PR TITLE
Fix InfoPanel Table Row

### PR DESCRIPTION
**Pull request by wadjih-bencheikh18**
closes https://github.com/zakodium-oss/react-science/issues/721

### CODE REVIEW

**Comment by wadjih-bencheikh18** [comment]
What's the difference between `bordered` and `hasBorder` in Table props?
Maybe we can remove the context hook
https://github.com/zakodium-oss/react-science/blob/287f1c3eff668e687ca5a19b04d23fd42185b6bf/src/components/table/Table.tsx#L33-L37

**Comment by stropitek** [comment]
I don't know. Are both used by the implementation?

**Comment by wadjih-bencheikh18** [comment]
> I don't know. Are both used by the implementation?

`bordered` is used directly by `HtmlTable` of blueprintjs
and `hasBorder` is the one used in the context
the two add border to the table so technically the two props do the same thing

**Comment by stropitek** [comment]
I think you can remove `hasBorder` all together and only keep the blueprintjs prop.

**Review by stropitek — APPROVED** [review]

**Pull request merged**
