### PR TITLE
fix: splitter not observe 'size' and 'closed' values changes

### PR DESCRIPTION
**Pull request by hamed-musallam**
- [X] https://github.com/zakodium-oss/react-science/issues/452

### CODE REVIEW

**Comment by stropitek** [comment]
> /cc @stropitek given you recently had a splitter library on your radar.

The library I was looking at is:
https://github.com/bvaughn/react-resizable-panels

I looked at it and one of the main limitation is that all sizes are expressed in percent. It does not seem possible to set a default panel size in pixel units, which I think we do in NMRium.

**Comment by targos** [comment]
https://github.com/bvaughn/react-resizable-panels/issues/47#issuecomment-1368108429

Please also review!

**Comment by stropitek** [comment]
> Please also review!

I don't think I'm ok with the API changes. I don't understand the point of having both `size` / `initialSize`, `closed` / `initialClosed` for properties which are uncontrolled.

The issue also is not very helpful because it describes the solution and not the problem.

@lpatiny will show me the root cause of the bug and I will make a second assessment.

@hamed-musallam if you could explain the original problem in the issue that would be helpful.

**Comment by hamed-musallam** [comment]
Currently, in NMRium we can control the size of the split panel from the general settings and it is per workspace and we always update the value once the `resize` is ends, the problem came when we switch between workspaces or change from the general setting the Splitter will not recognize the new value and only way is by forcing the Splitter to re-render by changes the `key` value, The same applied to the `closed` prosperity.

if we always change the `key` value this lead to re-render all the children.


What we have right now in this PR, is we keep default properties `initialClosed` and `intialSize`, and if we want to control these values from the parent component we can use `size` and `closed` properties

**Comment by stropitek** [comment]
> Take a look at this comment [#452 (comment)](https://github.com/zakodium-oss/react-science/issues/452#issuecomment-1457919090)

Why did you choose to add properties rather than keep (or rename) the `initialSize` and `initialClosed` properties?

**Comment by hamed-musallam** [comment]
Just to keep the old component interface as it is because most of the users will not control the `closed` and `size` properties which I think is a special case in NMRium so they will hardcode the values for these properties and will not change it.

**Comment by hamed-musallam** [comment]
I removed the  `initialSize` and `initialClosed` properties and keep the  `size` and `closed` properties and made the required changes, can you check the changes and if everything from your side looks good to you, can you merge it and create a new release from the package

**Review by stropitek — APPROVED** [review]
LGTM but I can't test the storybook. Next time please make sure to create a branch on the original repo rather than on a fork so that the cloudflare build works.

**Pull request merged**
