### PR TITLE
Create NMR dashboard

### PR DESCRIPTION
**Pull request by wadjih-bencheikh18**
closes : https://github.com/zakodium-oss/react-science/issues/762

https://762-create-a-dashboard-as-a.react-science.pages.dev/stories/?path=/story/components-nmrdashboard--from-fetch

### CODE REVIEW

**Comment by lpatiny** [comment]
@wadjih-bencheikh18 I just updated the stats to get lastMonth and last12Month information so I broker your code:

https://nmrdb.cheminfo.org/v1/getStats

Here are the new type definition

```json
interface Period {
  count: number;
  count1D: number;
  count2D: number;
  count1H: number;
  count13C: number;
  count1H1H: number;
  count1H13C: number;
  countOtherNuclei: number;
}
export interface PeriodYear extends Period {
  year: number;
  firstDayOfYearEpoch: number;
}

export interface PeriodMonth extends Period {
  month: number;
  firstDayOfMonthEpoch: number;
}

export interface ValueStats {
  total: number;
  last12Months: number;
  lastMonth: number;
}
export interface Stats {
  lastUpdate: number;
  nbFiles: ValueStats;
  nbNMRs: ValueStats;
  nb1D: ValueStats;
  nb2D: ValueStats;
  nbIsFid: ValueStats;
  nbIsFt: ValueStats;
  solvents: Array<{ count: number; solvent: string }>;
  formats: Array<{ count: number; format: string }>;
  nuclei: Array<{ count: number; nucleus: string }>;
  pulseSequences: Array<{ count: number; pulseSequence: string }>;
  users: Array<{ count: number; lastModified: number; username: string }>;
  sources: Array<{ count: number; lastModified: number; source: string }>;
  perMonths: PeriodMonth[];
  perYears: PeriodYear[];
}
```

**Comment by wadjih-bencheikh18** [comment]
Node.js 18 test is failing because of [nivo](https://nivo.rocks/)

**Comment by lpatiny** [comment]
@wadjih-bencheikh18  Thanks ! I did few text changes that I just commit.

Here are couple of comments: 

- [ ] As a dashboard I would like that most of the time (if screen size is big enough) we see all the information without having to sroll. If the screen is too small then it would go in a scrolling mode. So a responsive design will be needed.

- [ ] Resize of window should resize all the components

- [ ] Legend of the bar graph could be in the bottom of the chart

- [ ] Size of the numbers (on the top, Nb of spectra) should be much bigger

**Comment by lpatiny** [comment]
> Node.js 18 test is failing because of [nivo](https://nivo.rocks/)

This is not a problem

**Comment by lpatiny** [comment]
For the resize it works when you enlarge the window but not shrink it. Adding a minWidth:0 should help.

**Comment by lpatiny** [comment]
@wadjih-bencheikh18 One more change in the stats format ... see below the TS definition.

And one more request. Over the pie chart I would like to have 3 tabs: 'Last month' 'Last year' 'All time'. (actually it should look nice, don't know where to place those toggles).

image

```ts
interface Period {
  count: number;
  count1D: number;
  count2D: number;
  count1H: number;
  count13C: number;
  count1H1H: number;
  count1H13C: number;
  countOtherNuclei: number;
}
export interface PeriodYear extends Period {
  year: number;
  firstDayOfYearEpoch: number;
}

export interface PeriodMonth extends Period {
  month: number;
  firstDayOfMonthEpoch: number;
}

export interface ValueStats {
  total: number;
  last12Months: number;
  lastMonth: number;
}

export interface EntryStat {
  count: number;
  lastModified: number;
  value: string;
}
export interface ArrayStats {
  total: EntryStat[];
  last12Months: EntryStat[];
  lastMonth: EntryStat[];
}
export interface Stats {
  lastUpdate: number;
  nbFiles: ValueStats;
  nbNMRs: ValueStats;
  nb1D: ValueStats;
  nb2D: ValueStats;
  nbIsFid: ValueStats;
  nbIsFt: ValueStats;
  solvents: ArrayStats;
  formats: ArrayStats;
  nuclei: ArrayStats;
  pulseSequences: ArrayStats;
  usernames: ArrayStats;
  groupNames: ArrayStats;
  sources: ArrayStats;
  perMonths: PeriodMonth[];
  perYears: PeriodYear[];
}
```

**Comment by targos** [comment]
It has been incorporated, thanks!

**Pull request closed without merging**
